### ISSUE TITLE
is go 1.16 already out?

### ISSUE THREAD

**Issue by cyberhck** [lestrrat-go/backoff#29] opened 2021-02-16 11:30 UTC
https://github.com/lestrrat-go/backoff/blob/a3b6e88436592b684a3f330fb8bc53278dee3e69/go.mod#L3

This is giving me some issue when I'm installing the jwk package, it throws a bunch of errors on this package and it warns about 1.16 as well.

![image](https://user-images.githubusercontent.com/3640284/108057287-057d6f80-7085-11eb-87ee-47e2492dfd30.png)

**Comment by lestrrat** [comment] 2021-02-16 13:48
Ah, I use the RC release (go1.16rc1), so that might have just crept in.
But at the same time I don't understand why this would manifest itself when the CI is running against go1.14 and go1.15
What version of go are you using?

**Comment by cyberhck** [comment] 2021-02-16 14:58
I'm working on enterprise application and WILL NOT accept 1.16 just yet. I'm on 1.13 if that matters, please make a release which will fix this :)

**Comment by lestrrat** [comment] 2021-02-16 15:10
I'm working on my free time and WILL NOT accept 1.13. If that matters, please make a PR which will fix this.

Now, if you are seeing this on go1.14 or go1.15, I will see what I can do for go1.14 onwards (but I will ditch support for go1.14 once go1.16 comes out, which should be soon). Also you do realize go 1.13 is not supported by the Go team either https://golang.org/doc/devel/release.html#policy

Again, the CI is running against go1.14 and go1.15. it *should* work there. e.g. https://github.com/lestrrat-go/jwx/actions which uses this library is all green on go1.14 and go1.15

**Comment by lestrrat** [comment] 2021-02-16 22:04
Oh, go1.16 was just released https://blog.golang.org/go1.16
So the answer to the title of this issue is "Yes".

I'm willing to consider PRs, but for the time being I'm going to close this.

**Closed by lestrrat** 2021-02-16 22:04 UTC

**Comment by cyberhck** [comment] 2021-02-17 03:18
I never said I wanted 1.13 to work, my CI actually goes for 1.15 because that's the stable one, locally I'm on 1.13 because ubuntu has that at latest, releasing with something which isn't even released is always a bad idea anyway.

**Comment by lestrrat** [comment] 2021-02-17 03:21
I fail to see what you want me to do: I said it works for me on go1.14 and go1.15. Then I asked if the above problem reproduce with go 1.14 or go1.15. You just said you use go1.13. Now you are telling me your CI goes to 1.15.

So does it work on go 1.14/1.15? is this only on go 1.13?

**Comment by cyberhck** [comment] 2021-02-17 04:35
I wanted you to put the requirements to 1.15 at least, but I no longer need it as I'm trying to get go 1.16 to be approved for usage (I only need jwk to rsa.PublicKey parsing anyway which I'm doing manually for now), thanks for the help, there's nothing to do now as 1.16 is out :)

**Comment by lestrrat** [comment] 2021-02-17 04:39
Yeah, but in order to do this I need to know WHY things are happening. Why do you think changing go 1.16 to go 1.15 will magically fix your problems, when I can't reproduce it on my end? It could just be your environment.

You will not go far with OSS developers like me if you just come demanding to make changes that  you want without answering the questions asked.
You _still_ haven't responded. I still don't know if I have a problem in my CI that prevents it from uncovering the problem you are seeing, or if it is indeed go1.13, or something else.

**Comment by lestrrat** [comment] 2021-02-17 04:40
... And now you are telling me that this is about `jwk.PublicKey`, and you are filing this issue in `github.com/lestrrat-go/backoff`. I'm really confused. Please get  your story straight before demanding things out of volunteers

**Comment by cyberhck** [comment] 2021-02-17 09:54
I'm not sure why I'm getting a hostile vibe out here. The reason this library was even causing an issue for me was because jwx depends on backoff for some reason, it might be because it's calling it while doing some url fetching, I don't really know, and I don't intend to find out.

second, I'm not demanding anything, you've closed the issue, I've worked around the problem in my end, it probably was because I'm stuck in go 1.13 while you're far ahead, not everyone has privilege to be on the versions they want.

> but I no longer need it as I'm trying to get go 1.16 to be approved for usage

like I said, I'm not demanding anything, I opened issue at night time for me, next morning, I rather went into your sources of jwx and copied a bit of logic directly instead of trying to get my go version upgraded.

like I already said: I NO LONGER NEED ANYTHING. Thanks for the support, I know you're working on your free time as well, I'm not sure what gave you the impression of me demanding anything, I'm sure that wasn't my intention.

**Comment by lestrrat** [comment] 2021-02-18 01:15
Okay, I may have overreacted in your case, to which I apologize.

But I get tons of issues that just ask me to "fix it", and the most infuriating part of this is that I get no information that I ask. From my perspective it's always seems like I'm being told to "do what I want, but I won't do any research myself".

Furthermore, what really got me in your case is this comment https://github.com/lestrrat-go/backoff/issues/29#issuecomment-779891817. You may not have intended it that way, but that sounded exactly like "I have an arbitrary rule (I WILL NOT ACCEPT 1.16, with CAPS, which usually means you are "shouting" at me), I won't tell you why, I won't tell you if the problem is because of the environment or the code, but you need to fix it for me". I really wish you just responded to my question simply as, "I use go 1.13". I don't care that you can't accept 1.16. I want to know WHY this is happening.

**Comment by cyberhck** [comment] 2021-02-18 04:48
Thanks for changing the whole direction, unfortunately I'm in way different direction now that I've already solved the problem manually, if I get a chance I'll try to answer you by trying again and better bug report, but till then let's assume the problem is gone :)
